//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Kernel.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Kernel.Parser {

using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IKernelListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
public partial class KernelBaseListener : IKernelListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="KernelParser.file"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFile([NotNull] KernelParser.FileContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="KernelParser.file"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFile([NotNull] KernelParser.FileContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="KernelParser.expressionLine"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpressionLine([NotNull] KernelParser.ExpressionLineContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="KernelParser.expressionLine"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpressionLine([NotNull] KernelParser.ExpressionLineContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="KernelParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpression([NotNull] KernelParser.ExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="KernelParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpression([NotNull] KernelParser.ExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>Keyword</c>
	/// labeled alternative in <see cref="KernelParser.atom"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterKeyword([NotNull] KernelParser.KeywordContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>Keyword</c>
	/// labeled alternative in <see cref="KernelParser.atom"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitKeyword([NotNull] KernelParser.KeywordContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>StringLiteral</c>
	/// labeled alternative in <see cref="KernelParser.atom"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStringLiteral([NotNull] KernelParser.StringLiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>StringLiteral</c>
	/// labeled alternative in <see cref="KernelParser.atom"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStringLiteral([NotNull] KernelParser.StringLiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>SymbolLiteral</c>
	/// labeled alternative in <see cref="KernelParser.atom"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSymbolLiteral([NotNull] KernelParser.SymbolLiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>SymbolLiteral</c>
	/// labeled alternative in <see cref="KernelParser.atom"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSymbolLiteral([NotNull] KernelParser.SymbolLiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>NumberLiteral</c>
	/// labeled alternative in <see cref="KernelParser.atom"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumberLiteral([NotNull] KernelParser.NumberLiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>NumberLiteral</c>
	/// labeled alternative in <see cref="KernelParser.atom"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumberLiteral([NotNull] KernelParser.NumberLiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="KernelParser.pair"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPair([NotNull] KernelParser.PairContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="KernelParser.pair"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPair([NotNull] KernelParser.PairContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="KernelParser.string"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterString([NotNull] KernelParser.StringContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="KernelParser.string"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitString([NotNull] KernelParser.StringContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="KernelParser.number"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumber([NotNull] KernelParser.NumberContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="KernelParser.number"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumber([NotNull] KernelParser.NumberContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="KernelParser.numBin"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumBin([NotNull] KernelParser.NumBinContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="KernelParser.numBin"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumBin([NotNull] KernelParser.NumBinContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="KernelParser.numOct"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumOct([NotNull] KernelParser.NumOctContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="KernelParser.numOct"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumOct([NotNull] KernelParser.NumOctContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="KernelParser.numDec"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumDec([NotNull] KernelParser.NumDecContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="KernelParser.numDec"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumDec([NotNull] KernelParser.NumDecContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="KernelParser.numHex"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumHex([NotNull] KernelParser.NumHexContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="KernelParser.numHex"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumHex([NotNull] KernelParser.NumHexContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>BinaryPolar</c>
	/// labeled alternative in <see cref="KernelParser.complexBin"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBinaryPolar([NotNull] KernelParser.BinaryPolarContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>BinaryPolar</c>
	/// labeled alternative in <see cref="KernelParser.complexBin"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBinaryPolar([NotNull] KernelParser.BinaryPolarContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>BinaryComplex</c>
	/// labeled alternative in <see cref="KernelParser.complexBin"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBinaryComplex([NotNull] KernelParser.BinaryComplexContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>BinaryComplex</c>
	/// labeled alternative in <see cref="KernelParser.complexBin"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBinaryComplex([NotNull] KernelParser.BinaryComplexContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>BinaryNumber</c>
	/// labeled alternative in <see cref="KernelParser.complexBin"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBinaryNumber([NotNull] KernelParser.BinaryNumberContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>BinaryNumber</c>
	/// labeled alternative in <see cref="KernelParser.complexBin"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBinaryNumber([NotNull] KernelParser.BinaryNumberContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>OctalPolar</c>
	/// labeled alternative in <see cref="KernelParser.complexOct"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOctalPolar([NotNull] KernelParser.OctalPolarContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>OctalPolar</c>
	/// labeled alternative in <see cref="KernelParser.complexOct"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOctalPolar([NotNull] KernelParser.OctalPolarContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>OctalComplex</c>
	/// labeled alternative in <see cref="KernelParser.complexOct"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOctalComplex([NotNull] KernelParser.OctalComplexContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>OctalComplex</c>
	/// labeled alternative in <see cref="KernelParser.complexOct"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOctalComplex([NotNull] KernelParser.OctalComplexContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>OctalNumber</c>
	/// labeled alternative in <see cref="KernelParser.complexOct"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOctalNumber([NotNull] KernelParser.OctalNumberContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>OctalNumber</c>
	/// labeled alternative in <see cref="KernelParser.complexOct"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOctalNumber([NotNull] KernelParser.OctalNumberContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>DecimalPolar</c>
	/// labeled alternative in <see cref="KernelParser.complexDec"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDecimalPolar([NotNull] KernelParser.DecimalPolarContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>DecimalPolar</c>
	/// labeled alternative in <see cref="KernelParser.complexDec"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDecimalPolar([NotNull] KernelParser.DecimalPolarContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>DecimalComplex</c>
	/// labeled alternative in <see cref="KernelParser.complexDec"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDecimalComplex([NotNull] KernelParser.DecimalComplexContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>DecimalComplex</c>
	/// labeled alternative in <see cref="KernelParser.complexDec"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDecimalComplex([NotNull] KernelParser.DecimalComplexContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>DecimalNumber</c>
	/// labeled alternative in <see cref="KernelParser.complexDec"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDecimalNumber([NotNull] KernelParser.DecimalNumberContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>DecimalNumber</c>
	/// labeled alternative in <see cref="KernelParser.complexDec"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDecimalNumber([NotNull] KernelParser.DecimalNumberContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>HexadecimalPolar</c>
	/// labeled alternative in <see cref="KernelParser.complexHex"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHexadecimalPolar([NotNull] KernelParser.HexadecimalPolarContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>HexadecimalPolar</c>
	/// labeled alternative in <see cref="KernelParser.complexHex"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHexadecimalPolar([NotNull] KernelParser.HexadecimalPolarContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>HexadecimalComplex</c>
	/// labeled alternative in <see cref="KernelParser.complexHex"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHexadecimalComplex([NotNull] KernelParser.HexadecimalComplexContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>HexadecimalComplex</c>
	/// labeled alternative in <see cref="KernelParser.complexHex"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHexadecimalComplex([NotNull] KernelParser.HexadecimalComplexContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>HexadecimalNumber</c>
	/// labeled alternative in <see cref="KernelParser.complexHex"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHexadecimalNumber([NotNull] KernelParser.HexadecimalNumberContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>HexadecimalNumber</c>
	/// labeled alternative in <see cref="KernelParser.complexHex"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHexadecimalNumber([NotNull] KernelParser.HexadecimalNumberContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="KernelParser.realBin"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRealBin([NotNull] KernelParser.RealBinContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="KernelParser.realBin"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRealBin([NotNull] KernelParser.RealBinContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="KernelParser.realOct"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRealOct([NotNull] KernelParser.RealOctContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="KernelParser.realOct"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRealOct([NotNull] KernelParser.RealOctContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="KernelParser.realDec"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRealDec([NotNull] KernelParser.RealDecContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="KernelParser.realDec"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRealDec([NotNull] KernelParser.RealDecContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="KernelParser.realHex"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRealHex([NotNull] KernelParser.RealHexContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="KernelParser.realHex"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRealHex([NotNull] KernelParser.RealHexContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="KernelParser.imagBin"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterImagBin([NotNull] KernelParser.ImagBinContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="KernelParser.imagBin"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitImagBin([NotNull] KernelParser.ImagBinContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="KernelParser.imagOct"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterImagOct([NotNull] KernelParser.ImagOctContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="KernelParser.imagOct"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitImagOct([NotNull] KernelParser.ImagOctContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="KernelParser.imagDec"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterImagDec([NotNull] KernelParser.ImagDecContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="KernelParser.imagDec"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitImagDec([NotNull] KernelParser.ImagDecContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="KernelParser.imagHex"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterImagHex([NotNull] KernelParser.ImagHexContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="KernelParser.imagHex"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitImagHex([NotNull] KernelParser.ImagHexContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>BinaryRational</c>
	/// labeled alternative in <see cref="KernelParser.urealBin"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBinaryRational([NotNull] KernelParser.BinaryRationalContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>BinaryRational</c>
	/// labeled alternative in <see cref="KernelParser.urealBin"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBinaryRational([NotNull] KernelParser.BinaryRationalContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>BinaryInteger</c>
	/// labeled alternative in <see cref="KernelParser.urealBin"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBinaryInteger([NotNull] KernelParser.BinaryIntegerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>BinaryInteger</c>
	/// labeled alternative in <see cref="KernelParser.urealBin"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBinaryInteger([NotNull] KernelParser.BinaryIntegerContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>OctalRational</c>
	/// labeled alternative in <see cref="KernelParser.urealOct"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOctalRational([NotNull] KernelParser.OctalRationalContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>OctalRational</c>
	/// labeled alternative in <see cref="KernelParser.urealOct"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOctalRational([NotNull] KernelParser.OctalRationalContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>OctalInteger</c>
	/// labeled alternative in <see cref="KernelParser.urealOct"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOctalInteger([NotNull] KernelParser.OctalIntegerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>OctalInteger</c>
	/// labeled alternative in <see cref="KernelParser.urealOct"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOctalInteger([NotNull] KernelParser.OctalIntegerContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>DecimalRational</c>
	/// labeled alternative in <see cref="KernelParser.urealDec"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDecimalRational([NotNull] KernelParser.DecimalRationalContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>DecimalRational</c>
	/// labeled alternative in <see cref="KernelParser.urealDec"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDecimalRational([NotNull] KernelParser.DecimalRationalContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>DecimalInteger</c>
	/// labeled alternative in <see cref="KernelParser.urealDec"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDecimalInteger([NotNull] KernelParser.DecimalIntegerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>DecimalInteger</c>
	/// labeled alternative in <see cref="KernelParser.urealDec"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDecimalInteger([NotNull] KernelParser.DecimalIntegerContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>DecimalReal</c>
	/// labeled alternative in <see cref="KernelParser.urealDec"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDecimalReal([NotNull] KernelParser.DecimalRealContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>DecimalReal</c>
	/// labeled alternative in <see cref="KernelParser.urealDec"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDecimalReal([NotNull] KernelParser.DecimalRealContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>HexadecimalRational</c>
	/// labeled alternative in <see cref="KernelParser.urealHex"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHexadecimalRational([NotNull] KernelParser.HexadecimalRationalContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>HexadecimalRational</c>
	/// labeled alternative in <see cref="KernelParser.urealHex"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHexadecimalRational([NotNull] KernelParser.HexadecimalRationalContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>HexadecimalInteger</c>
	/// labeled alternative in <see cref="KernelParser.urealHex"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHexadecimalInteger([NotNull] KernelParser.HexadecimalIntegerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>HexadecimalInteger</c>
	/// labeled alternative in <see cref="KernelParser.urealHex"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHexadecimalInteger([NotNull] KernelParser.HexadecimalIntegerContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="KernelParser.symbol"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSymbol([NotNull] KernelParser.SymbolContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="KernelParser.symbol"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSymbol([NotNull] KernelParser.SymbolContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
} // namespace Kernel.Parser
